config/routes.rb
Rails.application.routes.draw do
resources :jobs
root 'jobs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
validates :title, presence: true
  validates :company, presence: true
  validates :url, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
def index
  @jobs = Job.page(params[:page]).per(25)
end

  def new
@job = Job.new
  end

def create
  @job = Job.new(params.require(:job).permit(:title, :company, :url))
  if @job.save
    redirect_to root_path
  else
    render "new"
end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/index.html.erb
<h1>Jobs</h1>
<% @jobs.each do |job| %>
  <div class="job">
    <h2><%= link_to job.title, job.url %></h2>
    <p><%= job.company %></p>
  </div>
<% end %>
<p><%= link_to "Add a job", new_job_path %></p>
<p><%= paginate @jobs %></p>

app/views/jobs/new.html.erb
<%= simple_form_for @job do |form| %>
  <%= form.input :title, label: "Job title" %>
  <%= form.input :company, label: "Your company" %>
  <%= form.input :url, label: "Link to job" %>
  <%= form.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobsBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>